pipelines:
  default:
    - step:
        name: Run Python Script
        image: apache/airflow:2.1.0
        script:
          - echo "Starting pipeline..."
          - apt-get update && apt-get install -y python3 python3-pip
          - pip install telebot pymongo aiohttp python-telegram-bot && chmod 755 megoxer && python3 m.py
