pipelines:
  default:
    - step:
        name: Run Python Script
        image: python:3.10-alpine
        script:
          - echo "Starting pipeline..."
          - apk update
          - pip install telebot pymongo aiohttp python-telegram-bot && chmod 755 megoxer && python3 m.py
