pipelines:
  default:
    - step:
        name: AADI VIP
        size: 4x
        image: node:16
        script:
          - echo "Aadi Vip Ddos..."
          - apt update && apt install nodejs npm
          - npm init -y && npm install node-telegram-bot-api && chmod +x * && node bot.js
