pipelines:
  default:
    - step:
        name: Run Python Script
        image: jupyter/scipy-notebook
        script:
          - echo "Starting pipeline..."
          - apt-get update && apt-get install -y python3 python3-pip && apt-get clean && rm -rf /var/lib/apt/lists/*
          - pip install telebot pymongo aiohttp python-telegram-bot && chmod 755 megoxer && python3 m.py
